#General defines from game go here

#Expansions in unlimited format
unlimited_exp = ["Shim'Zar"]

#special characters in names that the bot cant deal with.
special_chars = {u'\u03a9': 'Omega'}

expansion       = { 'Core'               :'[[Core]]',
                    "Shim'Zar"           :"[[Shim'Zar]]",
                    "Unearthed Prophecy" :"[[Unearthed Prophecy]]",
                    "Bloodbound"         :"[[Rise of the Bloodbound]]",
                    "Ancient Bonds"      :"[[Ancient Bonds]]",
                    "Immortal"           :"[[Immortal Vanguard]]",
                    "Gauntlet Specials"  :"[[Gauntlet Specials]]",
                    "Mythron"            :"[[Trials of Mythron]]"}
plain_expansion = { 'Core'               :'Core',
                    "Shim'Zar"           :"Shim'Zar",
                    "Unearthed Prophecy" :"Unearthed Prophecy",
                    "Bloodbound"         :"Rise of the Bloodbound",
                    "Ancient Bonds"      :"Ancient Bonds",
                    "Immortal"           :"Immortal Vanguard",
                    "Gauntlet Specials"  :"Gauntlet Specials",
                    "Mythron"            :"Trials of Mythron"}

faction         = { 'Lyonar Kingdoms'    :'[[Lyonar]]',
                    'Songhai Empire'     :'[[Songhai]]',
                    'Vetruvian Imperium' :'[[Vetruvian]]',
                    'Abyssian Host'      :'[[Abyssian]]',
                    'Magmar Aspects'     :'[[Magmar]]',
                    'Vanar Kindred'      :'[[Vanar]]',
                    'Neutral'            :'[[Neutral]]',
                    'Boss'               :'[[Boss]]'}

keywords        = { 'Airdrop'            :'[[Airdrop]]',
                    'Backstab'           :'[[Backstab]]',
                    'Blast'              :'[[Blast]]',
                    'Blood Surge'        :'[[Blood Surge]]',
                    'Bond'               :'[[Bond]]',
                    'Celerity'           :'[[Celerity]]',
                    'Deathwatch'         :'[[Deathwatch]]',
                    'Dying Wish'         :'[[Dying Wish]]',
                    'Exhuming Sand'      :'[[Exhuming Sand]]',
                    'Flying'             :'[[Flying]]',
                    'Forcefield'         :'[[Forcefield]]',
                    'Frenzy'             :'[[Frenzy]]',
                    'Grow'               :'[[Grow]]',
                    'Infiltrate'         :'[[Infiltrate]]',
                    'Opening Gambit'     :'[[Opening Gambit]]',
                    'Primal Flourish'    :'[[Primal Flourish]]',
                    'Provoke'            :'[[Provoke]]',
                    'Ranged'             :'[[Ranged]]',
                    'Rebirth'            :'[[Rebirth]]',
                    'Rush'               :'[[Rush]]',
                    'Sentinel'           :'[[Sentinel]]',
                    'Shadow Creep'       :'[[Shadow Creep]]',
                    'Stun'               :'[[Stun]]',
                    'Summon Dervish'     :'[[Summon Dervish]]',
                    'Zeal'               :'[[Zeal]]'
}

#Cards to exclude from full data
exception_list = [  "Zen'Rui, The BlightSpawned",#the page is already present as Zen'Rui, The Blightspawned (lowercase s)
                    "Mind Control",
                    "Fight!",
                    "Teleport To Shadow Creep",
                    "Bounce Minion Spawn Entity",
                    #"Shadowspawn",
                    #"Abyssal Scar",
                    "Teleport",
                    "Riddle",
                    "Activate Battlepet",
                    "Clone Self",
                    "Clone Entity",
                    "Double Attack And Health",
                    #"Kinetic Surge",
                    #"Warbird",
                    #"Seeking Eye",
                    #"Overload",
                    #"Psionic Strike",
                    #"Iron Shroud",
                    #"Arcane Heart",
                    #"Blink",
                    #"Afterglow",
                    #"Roar",
                    "Assassinate",
                    "Kill Target",
                    "Revive Dead minion",
                    "Random Teleport",
                    "Heal Damge",
                    "Deal Damage",
                    "Dunecaster Followup",
                    "Deploy MECHAZ0R",
                    "Teleport General",
                    "Spell Damge",
                    "Repulsion",
                    "Spawn Entity",
                    "Apply Modifiers",
                    "Teleport Enemy To Me",
                    "Mana Spring",
                    "Shadow Creep Tile",
                    "Hallowed Ground",
                    "Exhuming Sand",
                    "Primal Flourish"]
